# Generated by Django 4.1.1 on 2023-12-10 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='nombre',
            field=models.CharField(default='Cerveza X', max_length=100),
        ),
        migrations.AlterModelTable(
            name='store',
            table='Cervezas',
        ),
    ]
