# Generated by Django 4.1.1 on 2023-12-10 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_store_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='contacto',
        ),
        migrations.RemoveField(
            model_name='store',
            name='fecha_habilitacion',
        ),
        migrations.RemoveField(
            model_name='store',
            name='ubicacion',
        ),
    ]
